max_width = 100
tab_spaces = 4
edition = "2021"
use_small_heuristics = "Max"
newline_style = "Auto"
format_code_in_doc_comments = true
hard_tabs = true
indent_style = "Visual"
match_block_trailing_comma = true
imports_granularity = "Crate"
